services:
  - type: web
    name: ekat-markers
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
